name: 'Hashnode Blogs'

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update_blogs:
    name: 'Hashnode Latest Blogs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fetch Repository Contents'
        uses: actions/checkout@main

      - name: 'Hashnode Blog Action'
        uses: 'Shivam-Katare/hashnode-blog-action@main'
        with:
          HASHNODE_PUBLICATION_NAME: 'blog.hashnode.dev'
          POST_COUNT: 6
          FORMAT: 'list'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
